Class {
	#name : #FamixPythonIndexedFileAnchor,
	#superclass : #FamixPythonSourceAnchor,
	#traits : 'FamixTIndexedFileNavigation',
	#classTraits : 'FamixTIndexedFileNavigation classTrait',
	#category : #'Famix-Python-Entities-Entities'
}

{ #category : #meta }
FamixPythonIndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #FamixPythonSourceAnchor>
	<package: #'Famix-Python-Entities'>
	<generated>
	^ self
]
