Class {
	#name : #FamixPythonSourceTextAnchor,
	#superclass : #FamixPythonSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Python-Entities-Entities'
}

{ #category : #meta }
FamixPythonSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixPythonSourceAnchor>
	<package: #'Famix-Python-Entities'>
	<generated>
	^ self
]
