Class {
	#name : #FamixPythonUnknownSourceLanguage,
	#superclass : #FamixPythonSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Python-Entities-Entities'
}

{ #category : #meta }
FamixPythonUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixPythonSourceLanguage>
	<package: #'Famix-Python-Entities'>
	<generated>
	^ self
]
