Class {
	#name : #FamixPythonSourceLanguage,
	#superclass : #FamixPythonEntity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Famix-Python-Entities-Entities'
}

{ #category : #meta }
FamixPythonSourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixPythonEntity>
	<package: #'Famix-Python-Entities'>
	<generated>
	^ self
]
